#!/bin/sh

# Install: pip3 install pygments
# Style Gallery: https://help.farbox.com/pygments.html

case "$1" in
    *.el|*.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
    *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
    *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
    *.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass)
        pygmentize -f 256 -P style=dracula "$1";;

    *.bashrc|*.bash_aliases|*.bash_environment|*.profile)
        pygmentize -f 256 -P style=dracula -l sh "$1";;

    *)
        if grep -q "#\!/bin/bash" "$1" 2> /dev/null; then
            pygmentize -f 256 -P style=dracula -l sh "$1"
        else
            exit 1
        fi
esac

exit 0
