#!/bin/sh

# Install: pip3 install pygments
# Style Gallery: https://help.farbox.com/pygments.html

case "$1" in
    *.lsp|*.lisp|*.el)
        pygmentize -f 256 -P style=dracula -l lisp "$1";;

    *.py|*.pyx|*.pxi|.*pxd)
        pygmentize -f 256 -P style=dracula -l python "$1";;

    *.asm)
        pygmentize -f 256 -P style=dracula -l asm "$1";;

    *.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh)
        pygmentize -f 256 -P style=dracula -l c "$1";;

    *.txt)
        pygmentize -f 256 -P style=dracula -l text "$1";;

    *.json)
        pygmentize -f 256 -P style=dracula -l json "$1";;

    *.yml|*.yaml)
        pygmentize -f 256 -P style=dracula -l yaml "$1";;

    *.bashrc|*.bash_aliases|*.bash_environment|*.profile|*.conf|*.rc)
        pygmentize -f 256 -P style=dracula -l sh "$1";;

    *)
        pygmentize -f 256 -P style=dracula -l sh "$1";;
esac

exit 0
