(require 'package)
(package-initialize)
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives '("nongnu" . "https://elpa.nongnu.org/nongnu/")t)
;; (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(add-to-list 'package-archives '("orgmode". "https://orgmode.org/elpa/") t)


(defun pkg-install (package)
  (unless (package-installed-p package)
    (package-install package)))

(pkg-install 'auto-complete)
(pkg-install 'ace-jump-mode)
(pkg-install 'ace-window)
(pkg-install 'linum)
(pkg-install 'tramp)
(pkg-install 'slime)
(pkg-install 'rainbow-delimiters)
(pkg-install 'company)
(pkg-install 'projectile)
(pkg-install 'neotree)
(pkg-install 'magit)
(pkg-install 'dockerfile-mode)
(pkg-install 'bash-completion)

(pkg-install 'swift-mode)
(pkg-install 'rust-mode)

(pkg-install 'term)
(pkg-install 'ein)
(pkg-install 'eglot)
(pkg-install 'pyvenv)
(pkg-install 'yaml-mode)
(pkg-install 'markdown-mode)
(pkg-install 'buffer-move)

(pkg-install 'org)
(pkg-install 'org-contrib)


;; themes
(pkg-install 'color-theme)

(pkg-install 'abyss-theme)
(pkg-install 'almost-mono-themes)
(pkg-install 'ample-zen-theme)
(pkg-install 'anti-zenburn-theme)
(pkg-install 'arjen-grey-theme)
(pkg-install 'ayu-theme)
(pkg-install 'cherry-blossom-theme)
(pkg-install 'color-theme-cobalt)
(pkg-install 'color-theme-dg)
(pkg-install 'color-theme-github)
(pkg-install 'color-theme-heroku)
(pkg-install 'color-theme-sanityinc-solarized)
(pkg-install 'color-theme-sanityinc-tomorrow)
(pkg-install 'color-theme-tango)
(pkg-install 'cyberpunk-theme)
(pkg-install 'doom-themes)
(pkg-install 'dracula-theme)
(pkg-install 'enlightened-theme)
(pkg-install 'gruber-darker-theme)
(pkg-install 'gruvbox-theme)
(pkg-install 'hemisu-theme)
(pkg-install 'heroku-theme)
(pkg-install 'poet-theme)
(pkg-install 'soothe-theme)
(pkg-install 'spacemacs-theme)
(pkg-install 'zenburn-theme)



(require 'auto-complete)
(require 'ace-jump-mode)
(require 'linum)
(require 'tramp)
(require 'slime)
(require 'rainbow-delimiters)
(require 'company)
(require 'projectile)
(require 'neotree)
(require 'ace-window)
(require 'buffer-move)
(require 'term)
(require 'ein)
(require 'ein-output-area)
(require 'eglot)
(require 'pyvenv)
(require 'yaml-mode)
(require 'markdown-mode)
(require 'org)
(require 'org-agenda)
(require 'org-tempo)
(require 'org-expiry)
(require 'mouse)
